version: "3.8"
services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  backend:
    build:
      context: ./servercontainer
    env_file:
      - ./.env  
    command: >
      sh -c "python3 manage.py makemigrations syspointage &&
      python3 manage.py migrate syspointage &&
      gunicorn --workers=17 --timeout=1200 --bind 0.0.0.0:${BACKEND_PORT} pointage.wsgi"   
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    container_name: django
    restart: always
    depends_on:
      - redis

  frontend:
    build:
      context: ./reactcontainer
    environment:
      - REACT_APP_URL=http://192.168.23.10/api/
      - REACT_APP_URL2=http://192.168.23.10/
    volumes:
      - react_build:/reactcontainer/build

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  
  
    volumes:
      # - ./ac:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh
      - react_build:/var/www/react
      
    depends_on:
      - backend
      - frontend
    env_file:
      - ./.env   
    #command: /etc/nginx/entrypoint.sh ${FRONTEND_PORT} ${SERVER_NAME} ${API_URL}
    restart: always

  mysql:
     image: mysql:latest
     container_name: mysql-db
     environment:
       MYSQL_ROOT_HOST: '%'
       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
     ports:
       - "3306:3306"   

volumes:
  postgres:
  react_build:
