from django.urls import path, re_path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)
from . import_csv import * 
from . calcul_func import *
from . manager_valideurs import managers_valideurs
from . import_vb import Rapportpaie
from . workflow import *
from . front_select_methods import *
from . supervision import *
from . accueil import *
from . demandes import *
from . views import *
from . import views

urlpatterns = [
 path('api/UsersOfChef/<int:pk>/', UsersOfChef.as_view(), name="Employés"),
 path('api/listvalidation/<int:pk>/<motif>', ListValidation.as_view(), name="congé list"),
 path('api/validation/<int:pk>/<int:user>', Validationworkflow.as_view(), name="update"),
 path('api/refusworkflow/<int:idconge>', refusworkflow.as_view(), name="refus workflow"),
 path('api/user/', Userlist.as_view(), name="Affichage la menu déroulante des employés"),
 path('api/userselect/', UserlistForSelect.as_view(), name="Affichage multiselect employés"),
 path('api/motifselect/', motiflistForSelect.as_view(), name="Affichage multiselect motif"),
 path('api/create/', CustomUserCreate.as_view(), name="Ajouter Employé"),
 path('api/userdelete/<int:pk>',UserDelete.as_view(), name="Supprimer employé"),
 path('api/user/<int:pk>', UpdateUser.as_view(), name="Modifier employé"),
 path('api/userofdepartements/', UsersOfDepartement.as_view(), name="Affichage la menu déroulante des employés"),
 path('api/depuser/', Usersdepequipe.as_view(), name="Affichage des employés des dep"),
 path('api/Testuserofdepartements/', TestUsersOfDepartement.as_view(), name="Affichage la menu déroulante des employés"),
 path('api/employespartis/',EmployesPartis.as_view(),name="Employés partis"),
 path('api/quitteremploye/<id>/<motif>',QuitterEmploye.as_view(),name="cliquer sur l'icone parti employé"),
 path('api/role/' , views.Rolelist.as_view(), name="role"),
 path('api/role/<int:pk>' , views.Roleupdate.as_view(), name="role"),
 path('api/pointeuse/' , views.Pointeuselist.as_view(), name="pointeuse"),
 path('api/pointeuse/<int:pk>' , views.Pointeuseupdate.as_view(), name="pointeuse"),
 path('api/pointage/' , views.Pointagelist.as_view(), name="Affichage la liste de pointage"),
 path('api/createpointage/' , views.CreatePointage.as_view(), name="Ajouter pointage"),
 path('api/updatepointage/<int:pk>' , views.UpdatePointage.as_view(), name="pointage"),
 path('api/deletpointage/<int:pk>',views.DeletePointage.as_view(),name="Supprimer pointage"),
 path('api/pointage/<int:pk>' , views.PointageRetrieve.as_view(), name="Sélectionner un pointage"),
 path('api/motif/' , views.Motiflist.as_view(), name="motif"),
 path('api/motif/<int:pk>' , views.Motifupdate.as_view(), name="motif"),
 path('api/Absence/',views.AbsencesList.as_view(),name="Liste des absences"),
 path('api/Absence/<int:pk>', views.AbscenceUpdate.as_view(),name="absence by Id"),
 path('api/arbo/',views.ArborescenceList.as_view(),name="Liste des arborescences"),
 path('api/arbo/<int:pk>',views.ArborescenceUpdate.as_view(),name="absences"),
 path('api/horaire/' , views.Horairejourlist.as_view(), name="liste des horaires"),
 path('api/horaire/<int:pk>' , views.HoraireJourupdate.as_view(), name="horaire par ID"),
 path('api/plansemaine/' , views.Plansemainelist.as_view(), name="liste de planning semaine"),
 path('api/plansemaine/<int:pk>' , views.plansemaineupdate.as_view(), name="planning semaine par ID"),
 path('api/departementbyid/<int:pk>' , views.departementbyid.as_view(), name=" departement par ID"),
 path('api/managerscreate/' , views.ManagersCreate.as_view(), name=" ManagersCreate"),
 path('api/contrats/',views.ContratList.as_view(),name="contrats"),
 path('api/contrats/<int:pk>' , views.contratupdate.as_view(), name="contrats"),
 path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
 path('api/token/verify/', views.MyTokenVerifyView.as_view(), name='token_verify'),
 path('api/JourFerie/',views.JoursFeriesList.as_view(),name="JourFerie"),
 path('api/JourFerie/<int:pk>', views.JourFeriéUpdate.as_view(),name="JourFerie"),
 path('api/demendeconges/<int:pk>/<type>/<date1>/<date2>/<soldenouveau>/<nouveausoldemaladie>' ,Demandeconges.as_view(), name="demande Congé ou autorisation ou mission ou téletravail"),
 path('api/demanderh/<int:pk>' , AffichageDemandeRH.as_view(), name="demanderh"),
 path('api/demandepointage/<int:pk>' , AffichageDemandePointage.as_view(), name="demande pointage"),

 path('api/ChartParJournee/<date1>/<date2>/<nbcc>/<nbaa>/<nbrr>/<nbabse>/<nbmis>/',views.ChartsParJourneeDynamique.as_view(),name='Chef/rh indicateurs=>affichage chart'),
 path('api/ChartAbsenceList/<int:pk>',views.ChartAbsenceList.as_view(),name='Chef/rh indicateurs'),
 path('api/token/',views.MyTokenObtainPairView.as_view(),name='connexion'),
 path('api/rapportpointage/<date1>/<date2>/',views.RapportPointage.as_view(),name='rapport pointage'),
 path('api/rapportjour/<date1>/<date2>/',views.RapportJournalier.as_view(),name='rapport journalier'),
 path('api/rapportpaie/<date1>/<date2>/',Rapportpaie.as_view(),name='rapport paie'),
 path('api/rapportabsence/<date1>/<date2>/',views.RapportAbsences.as_view(),name='rapport absence'),
 path('api/rapportsemaine/<date1>/<date2>/',views.RapportSemaine.as_view(),name='rapport semaine'),
 path('api/rapportsynthese/<date1>/<date2>/',views.RapportSynthese.as_view(),name='rapport synthese'),
 path('api/accuiel/<int:pk>',Accueil.as_view(),name="accueil"),
 path('api/ticketrestau/<int:pk>',Ticketrestau.as_view(),name="ticketrestau"),
 path('api/lastpointageauj/<int:pk>',LastPointageTodayView.as_view(),name="lastpointageauj"),
 path('api/pauseauj/<int:pk>', pauseaujourdhui.as_view() , name='pauseaujourd'),
 path('api/HistoriqueDemendesConges/<int:pk>',views.HistoriqueDemendesConges.as_view(),name="accueil"),
 path('api/SupressionConge/<int:pk>',views.SupressionConge.as_view(),name='Supression de Conge/autorisation/mission/téletravail'),
 path('api/RetrieveUpdateConge/<id>/<validation>/<validationrh>/<validationrh2>',views.ValidationConge.as_view(),name='Validation de Conge ou autorisation ou mission ou téletravail'),
 path('api/RefusConge/<int:pk>',views.RefusConge.as_view(),name='Refus de Congé ou autorisation ou mission ou téletravail'),
 path('api/SendMail',views.SendMai.as_view(),name='envoi email'), 
 path('api/SearchpourDemandeConge/<id>/<nbjourretires>/<nombrejours_ouvres>/<justifie>/<date1>/<date2>/<congemaladie>/<matindebut>/<matinfin>',views.SearchpourDemandeConge,name='calcul dans la demande de congé'),
 path('api/CreateplaningByDep/',views.CreateplaningByDep.as_view(),name='ajouter planning par département'),
 path('api/GetUserById/<int:pk>',views.GetUserById.as_view(),name="sélectionner employé"),
 path('api/RapportMensuelle/<date1>/<date2>/',views.RapportMensuelle.as_view(),name="Rapport Mensuel"),
 path('api/RapportAnuellement/<date1>/<date2>/',views.RapportAnuellement.as_view(),name="Rapport Annuel"),
 path('api/Mouchardcreate/<previous>/<new>/<idemploye>/<idpersonne>/<obj>',views.Mouchardcreate.as_view(),name="Ajouter au mouchard"),
 path('api/managers/<int:workflow_id>/', managers_valideurs.as_view(), name='managers-by-id'),
 path('api/MouchardList/',views.MouchardList.as_view(),name='Affichage mouchard'),
 path('api/AffichageDemendesConges/<int:pk>',AffichageDemendesConges.as_view(),name='Affichage les Demandes  de Conge/autorisation/mission'),
 path('api/SelectcongebyId/<int:pk>',views.SelectcongebyId.as_view(),name="sélectionner congé validé "),
 path('api/selectworkdep/<int:dep>',WorkflowByIdDepAPIView.as_view(),name="sélectionner workflow par departement "),
 path('api/planning/' , views.Planninglist.as_view(), name="affichage planning"),
 path('api/planning/<int:pk>' , views.PlanningDelete.as_view(), name="sélectionner planning"), 
 path('api/GetUsersbyplanings/<int:pk>',views.GetUsersbyplanings.as_view(),name="affichage les employés de planning sélectionné"),
 path('api/updateUserbyplanning/<idplanning>/<iduser>/<idplaningactuelle>',views.updateUserbyplanning.as_view(),name="modifier planning d'employé"),
 path('api/RemoveUserbyplanning/<iduser>/<idplaningactuelle>',views.RemoveUserbyplanning.as_view(),name="Supprimer un affectation de planning à employé"),
 path('api/export_mensuelle_excel/<date1>/<date2>/', views.export_mensuelle_excel.as_view(), name=""),
 path('api/CreateListTeletravail/',views.CreateListTeletravail.as_view(),name=""),
 path('api/UpdateDeleteTeletravail/<int:pk>', views.UpdateDeleteTeletravail.as_view(),name="téletravail"),
 #path('SendAuxchefs/',views.SendAuxchefs,name="SendAuxchefs"),
 path('api/ImportPointageCSV/',ImportPointageCSV.as_view(),name="Importer fichier de pointage csv"),
 path('api/ImportUserCSV/', ImportUserCSV.as_view(),name="Importer fichier de user csv"),
 path('api/TeletravailListbyId/',views.TeletravailListbyId.as_view(),name="affichage téletravails pour l'employé connecté"),
  path('api/equipeselect/<int:idequipe>', user_equipe_ForSelect.as_view(),name="liste des utilisateur for select "),
 path('api/equipe/',views.createequipe.as_view(),name="equipe"),
 path('api/updateequipe/<int:pk>', views.updateequipe.as_view(),name="update equipe"),
path('api/setequipe/', SetEquipeView.as_view(), name='set_equipe'),
 path('api/createlistsite/',views.createlistsite.as_view(),name="site"),
 path('api/updatedeletesite/<int:pk>', views.updatedeletesite.as_view(),name="absence by Id"),
 path('api/ListSite_ForSelect/', ListSite_ForSelect.as_view(),name="Affichage le menu déroulant des sites"),
  path('api/equipeselect/', equipeselect.as_view(),name="Affichage le menu déroulant des equipe"),
 path('api/historiquecreate/<previous>/<new>/<idemploye>/<idpersonne>/<soldeajoute>/<commentaire>',views.Historiquecreate.as_view(),name="historique de solde ajouté"),
 path('api/HistoriqueList/',views.HistoriqueList.as_view(),name="Affichage la liste d'historique solde"),
 path('api/updateSoldeUser',views.updateSoldeUser.as_view(),name="Ajouter solde à l'employé"),
 path('api/DeleteHistorique_solde/<id>',views.DeleteHistorique_solde,name="Supprimer solde (historique)"),
 path('api/ListPointageByDepartement/<int:pk>',views.ListPointageByDepartement.as_view(),name="Chef/Rh Affichage la liste de pointages"),
 path('api/Emailscreate/',views.Emailscreate.as_view(),name=""),
 path('api/GetEmails/',views.GetEmails.as_view(),name="GetEmails"),
 path('api/LesretardsParSemaine/<int:pk>/<employes>',views.LesretardsParSemaine.as_view(),name='LesretardsParSemaine'),
 path('api/Getarbobyids/',views.Getarbobyids.as_view(),name="affichage la  liste de départements"),
 path('api/AnnullerCongeEmploye/<int:pk>',views.AnnullerCongeEmploye.as_view(),name='employé annulle son congé'),
 path('api/rapportconges',views.RapportConges.as_view(),name='rapport de congés'),
 path('api/AffichageContrats/<int:pk>/', AffichageContrats.as_view(), name="Employés"),
 path('api/AffichageEmployesbyDepartement/<int:pk>', AffichageEmployesbyDepartement.as_view(), name="AffichageEmployesbyDepartement"),
 path('api/managersbyid/<int:dep>',managersbyid.as_view(),name='rapport de manager'),
 path('api/departments/',views.DepartmentHierarchyView.as_view(),name='departementslist'),
 path('api/pause/', createlistpause.as_view(), name="create list pause"),
 path('api/pause/<int:pk>', updatedeletepause.as_view(), name="update delete pause"),
 path('api/workflowconge/create/', views.WorkflowCongeCreateAPIView.as_view(), name='create_workflow_conge'),
 path('api/rapportwfm/<int:id>', rapportwfm.as_view(), name="rapport wfm "),
  path('api/Pointageaujourdhui/<int:pk>', Pointageaujourdhui.as_view(), name="Pointage aujourdhui"),
  path('api/PointagesEmploye/<id>', PointagesEmploye.as_view(), name="Pointages d'employé"),
  path('api/Pointagesofchefs/<int:pk>',Pointagesofchefs.as_view(),name="affichage les pointages des employés de chef "),
  path('api/get-utc-time/<int:id>', get_utc_offset, name='get_utc_time'),
  path('api/AffichageDemendesAut/<int:pk>',AffichageDemendesAut.as_view(),name='Affichage les Demandes  de autorisation'),

 ]
 